#!/bin/bash

DragapultBinary="/usr/local/opt/dragapult"

_getReleaseVersion() {
  curl -sL "https://api.github.com/repos/diareuse/dragapult/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'
}

_getOsType() {
 if [[ "$OSTYPE" == "linux-gnu"* ]]; then # linux
   echo "dragapult-linux"
 elif [[ "$OSTYPE" == "darwin"* ]]; then # macOS
   echo "dragapult-mac"
 else
   echo "Your system is not supported. If you're using Windows use powershell scripts"
   exit 1
 fi
}

_updateSelf() {
  DragapultVersion="$(_getReleaseVersion)"
  echo "Updating to version '$DragapultVersion'"
  if [ ! -d "/usr/local/opt" ]; then
    mkdir -p "/usr/local/opt"
  fi

  wget -q -O $DragapultBinary -c "https://github.com/diareuse/dragapult/releases/download/${DragapultVersion}/$(_getOsType)"
  chmod 755 $DragapultBinary

  if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "Validating binary at $DragapultBinary"
    xattr -r -d com.apple.quarantine $DragapultBinary
  fi

  echo "Update finished successfully"
}

while getopts 'u' flag; do
  case "${flag}" in
    u) _updateSelf
       exit 0;;
  esac
done

if [ ! -f "$DragapultBinary" ]; then
  _updateSelf
fi

## Run the downloaded binary on our behalf
$DragapultBinary $@
